name: Branch Name Validation

on:
  push:
    branches-ignore:
      - main

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ ! $BRANCH_NAME =~ ^feature/ ]]; then
            echo "Branch names must start with 'feature/'"
            exit 1
          fi
          echo "Branch name is valid."