name: Enforce Branch Naming

on:
  push:
    branches-ignore:
      - main
      - 'feature/**'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          if [[ ! "$GITHUB_REF" =~ refs/heads/feature/ ]]; then
            echo "::error::Branch name must start with 'feature/'"
            exit 1
          fi
